# Generated by Django 5.0.14 on 2026-04-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_add_notification_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("offer_received", "Offer Received"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_rejected", "Offer Rejected"),
                    ("outbid", "Outbid"),
                    ("auction_won", "Auction Won"),
                    ("order_paid", "Order Paid"),
                    ("order_shipped", "Order Shipped"),
                    ("order_delivered", "Order Delivered"),
                    ("new_bid", "New Bid"),
                    ("price_drop", "Price Drop"),
                    ("review_received", "Review Received"),
                    ("dispute_opened", "Dispute Opened"),
                    ("dispute_resolved", "Dispute Resolved"),
                    ("search_alert", "Search Alert"),
                ],
                max_length=20,
            ),
        ),
    ]
