# Generated by Django 6.0.3 on 2026-04-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_dispute"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="escrow_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "Held in Escrow"),
                    ("released", "Released to Seller"),
                    ("refunded", "Refunded to Buyer"),
                    ("disputed", "Frozen — Dispute Active"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="protection_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
