# Generated by Django 6.0.3 on 2026-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_seed_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("closed", "Closed"),
                ],
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
    ]
