# Generated by Django 6.0.3 on 2026-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_created_at_alter_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="flagged_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
