# Generated by Django 6.0.3 on 2026-04-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_verified_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
